In [1]:
import numpy as np
import numpy.random
import numpy.linalg
from numpy.linalg import *
from numpy import *

In [2]:
dim = 4

alpha, beta, sigma = [3, 0.2, 0.05] 

# g = metric
def g(x, y): return np.trace(x.T @ y)


def sym(x):
    return 0.5 * (x + x.T)


# P_x Z
def project_tangent_space(x, z):
    return z - x @ (sym(x.T @ z))


def retraction(x, tau):
    return qr(x + tau)[0]

# A = symmetric
A = np.array([[1 + ( (i & j)  for j in range(dim)] for i in range(dim)])

# N = diagonal
N = np.eye(dim)

    
def cost_function(x):
    return np.trace(x.T @ A @ x @ N)

def gradient(x):
    return project_tangent_space(x, (A + A.T) @ x @ N)

SyntaxError: invalid syntax (<ipython-input-2-aa5399c5ae65>, line 22)

# Tangent space

$$T_X(M) = \{ Z \mid X^T Z + Z^T X = 0 \}$$


In [37]:
def armijo_step(x_cur):
    m = 0
    while True:
        # we choose eta as negative of gradient:
        eta = -1.0 *  gradient(x_cur)
        r = retraction(x_cur, alpha*(beta**m)*eta)
        dot = g((-1.0 * sigma * gradient(x_cur)), ((beta **m) * alpha * eta))
        if cost_function(x_cur) - cost_function(r) >= dot:
            return alpha*(beta**m)
        print("m: %s" % m)
        m += 1

        
def run_gradient_descent_armijo(x0):
    x_cur = x0
    XS = [x_cur]
    YS = [cost_function(x_cur)]
    ETAS = []
    i = 0
    while i <= 10000:
        #eta_k is chosen as -grad f(x_k) which is gradient-related
        eta_k = -1.0 * gradient(x_cur)
        ETAS.append(eta_k)
        # if np.linalg.norm(eta_k) < 1e-4: break
        
        t_k = 1e-1
        # t_k = armijo_step(x_cur)
        x_cur = retraction(x_cur, t_k*eta_k)
        XS.append(x_cur)
        YS.append(cost_function(x_cur))
        i += 1
    return (np.array(XS), np.array(YS), np.array(ETAS))

In [38]:
np.random.seed(0)

def random_ortho():
    return qr(np.random.rand(dim, dim))[0]

begin = random_ortho()

(xs, ys, etas) = run_gradient_descent_armijo(begin)
print("xs: ")
print(xs[-1])
print("A diagonalized (roughly):")
print(xs[-1].T @ A @ xs[-1])
print("A original: ")
print(A)

xs: 
[[-0.41701418 -0.30427949  0.57378218  0.63583581]
 [-0.32191274 -0.3643801   0.42122447 -0.76561693]
 [-0.73223605  0.66994742 -0.10234467 -0.06727839]
 [-0.43162684 -0.57079908 -0.69488814  0.07083191]]
A diagonalized (roughly):
[[ 3.31977485  0.86572068  1.99531204  0.79098995]
 [-0.9868222  -0.28137205 -0.58728662 -0.25188892]
 [-1.09751154 -0.37764573 -0.63745819 -0.32528142]
 [ 1.51032138 -0.69686344  1.17242944 -0.4009446 ]]
A original: 
[[0 1 0 1]
 [0 0 2 2]
 [0 1 2 3]
 [0 0 0 0]]


In [26]:
import torch
X = torch.ndarray

AttributeError: module 'torch' has no attribute 'ndarray'